workflows:
  flutter-build:
    name: Build Flutter APK
    environment:
      flutter: "3.19.6"
    working_directory: Buscomfy_App
    scripts:
      - flutter pub get
      - flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
